feat: print token of given secret name

diff --git a/kubernetes/Makefile b/kubernetes/Makefile
--- a/kubernetes/Makefile
+++ b/kubernetes/Makefile
@@ -8,7 +8,7 @@ else
   TARGET_DIR := $(K8S_RESOURCES_DIR)
 endif
 
-.PHONY: apply-namespaces apply-all apply update-image
+.PHONY: apply-namespaces apply-all apply update-image print-decoded-token help
 
 .DEFAULT_GOAL := help
 
@@ -47,6 +47,22 @@ update-image: ## Update tag of given IMAGE to TAG of all resources defined in YA
 				fi; \
 			fi; \
 		done
+
+print-decoded-token: ## Print base64 decoded token of secret which is passed as NAME
+	@if [ -z "$(NAME)" ]; then \
+		echo "Usage: make print-base64-token NAME=<secret-name>"; \
+		exit 1; \
+    fi
+	@NAME=$(NAME) ; \
+	NAMESPACE=$$(kubectl get secrets --all-namespaces --output jsonpath='{range .items[?(@.metadata.name=="'"$$NAME"'")]}{.metadata.namespace}{"\n"}{end}') ; \
+	if [ -z "$$NAMESPACE" ]; then \
+		echo "Secret $$NAME not found in any namespace." >&2 ; exit 1 ; \
+	fi ; \
+	TOKEN=$$(kubectl get secret $$NAME -n $$NAMESPACE -o jsonpath='{.data.token}' | base64 --decode) ; \
+	if [ -z "$$TOKEN" ]; then \
+		echo "Token not found in secret $$NAME in namespace $$NAMESPACE." >&2 ; exit 1 ; \
+	fi ; \
+	echo $$TOKEN
 
 help: ## Show this help
 	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z0-9._-]+:.*?## / {printf "\033[1m\033[36m%-24s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
